### ISSUE TITLE
ubuntu 15.04 vivid vervet下找不到正确下载源

### ISSUE THREAD

**Issue by lan2720** [justzx2011/openyoudao#50]
```
W: Failed to fetch http://ppa.launchpad.net/justzx2011/openyoudao-v0.4/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found
```
已经在sourse.list中加入了
deb http://ppa.launchpad.net/justzx2011/openyoudao-v0.4/ubuntu trusty main 
deb-src http://ppa.launchpad.net/justzx2011/openyoudao-v0.4/ubuntu trusty main
但是，系统仍然去fetch dist/目录下的vivid文件夹，想问问如何设置才能找到trusty/main呢？

**Comment by justzx2011** [comment]
可以通过setup.py  安装：
setup.py:
    git clone https://github.com/justzx2011/openyoudao
    python setup.py build 
    sudo python setup.py install

**Comment by lan2720** [comment]
@justzx2011 弄好了，谢谢！
